### ISSUE TITLE
hod-readthedocs: difference between hod and hanythingondemand modules

### ISSUE THREAD

**Issue by epauwels** [hpcugent/hanythingondemand#169]
The difference between the hod and hanythingondemand modules is nowhere addressed in the documentation.

**Comment by boegel** [comment]
That's mostly because this is specific to our systems, it's just a detail of how HOD is installed on the HPC-UGent systems.

The HPC-UGent site-specific aspects of HOD are covered in http://hpc.ugent.be/userwiki/index.php/Tips:Software:hanythingondemand (note to others: may not be accessible for everyone).
